# print("                                                              ")
print("I belong here.")
print("I also belong here.")
print("Me too!")
# print("                                                              ")